### ISSUE TITLE
Cannot enrol a new device: `POST` to `/app/v1/welcome` endpoint no longer works

### ISSUE THREAD

**Issue by peter-kerr1** [eidorb/ubank#4]
The POST request at [the following line](https://github.com/eidorb/ubank/blob/eef563e3102bba9acb96f65bdd873bfe6b616178/ubank.py#L193) no longer works. The following response is given:

```
{
    "dialog": {
        "type": "Simple",
        "data": {
            "type": "error",
            "message": "Please update your app"
        },
        "buttons": [
            {
                "type": "Default",
                "data": {
                    "text": "No",
                    "secondary": "True"
                }
            },
            {
                "type": "ToAppStore",
                "data": {
                    "text": "Update"
                }
            }
        ]
    },
    "message": "Please update the app to use this feature"
}
```

I tried changing `app_version` to `11.43.1` (the current [app version](https://apps.apple.com/au/app/ubank-money-app/id1449543099) as at 2024-08-07), but that didn't fix the problem.

Hoping this is just a simple fix, because this tool will make my life very convenient :)

**Comment by jakepronger** [comment]
Facing same issue UBank may have updated their backend or the way logins work. Hoping this is a simple fix as well because I would also find this tool really helpful, have been looking at it myself.

**Comment by jakepronger** [comment]
I've been looking at this for a while today mostly looking at the code and comparing it with developer tools and even using my phone monitoring the http requests. I think I may have just gotten it to work by adding `"x-api-version": "30",` below line 189 to the headers param. I was just looking at the request and thought why not try adding that since I saw it in the dev tools and boom.

**Comment by peter-kerr1** [comment]
Epic, that works! Thanks @jakepronger. I have a question for you - how do you find the rest of the endpoints available? Because they don't seem to match the format of the endpoints defined in the [CDR API](https://consumerdatastandardsaustralia.github.io/standards/#banking-apis).

**Comment by jakepronger** [comment]
I've just used the project for the first time plan to use this for an idea of mine. Have you used this project before? What endpoints are you looking for in particular or don't match in the defined article? I will take a deeper look later.

**Comment by peter-kerr1** [comment]
I've never used this project before, since I wasn't able to generate an auth key until you mentioned this fix. Ideally, I want to download a `.csv` file of the last week's worth of transactions on one of my accounts. Failing that, a list of transactions in `JSON` format would do fine. I don't really have the time to reverse-engineer which endpoint(s) to use myself, so I may have to abandon the idea...

**Comment by jakepronger** [comment]
Interesting, I also want to do the same as well as automate scheduled payments (at specific times) and because payments can't be scheduled now from savings accounts (coming into effect in september). So I've been debugging with that and I've been able to make an automated transfer. Will look into it more as well as looking at transaction history but I believe it is there. You can literally do anything with this I believe. I can keep you posted when I work on this more and will also look at making a merge request if possible with the response api fix.

**Comment by jakepronger** [comment]
> I've never used this project before, since I wasn't able to generate an auth key until you mentioned this fix. Ideally, I want to download a `.csv` file of the last week's worth of transactions of one of my accounts. Failing that, a list of transactions in `JSON` format would do fine. I don't really have the time to reverse-engineer which endpoint(s) to use myself, so I may have to abandon the idea...

I'm making like a utility python script that uses this to make transactions and read transaction information. You can pull up the transaction information of a certain account using its ID.

**Comment by peter-kerr1** [comment]
> I'm making like a utility python script that uses this to make transactions and read transaction information. You can pull up the transaction information of a certain account using its ID.

If you're willing to share what you've got when you're done, I'd love to take a look!

**Comment by jakepronger** [comment]
> > I'm making like a utility python script that uses this to make transactions and read transaction information. You can pull up the transaction information of a certain account using its ID.
> 
> If you're willing to share what you've got when you're done, I'd love to take a look!

hey man feel free to dm me on discord (jakepronger) or email jakepronger31@gmail.com. I may also be looking at integrating into Commbank API for net codes and am working on other projects that will link up to the ubank stuff. So I will swing around too it. I'll lyk.

**Comment by peter-kerr1** [comment]
> hey man feel free to dm me on discord (jakepronger) or email [jakepronger31@gmail.com](mailto:jakepronger31@gmail.com). I may also be looking at integrating into Commbank API for net codes and am working on other projects that will link up to the ubank stuff. So I will swing around too it. I'll lyk.

I've sent you a friend request on Discord

**Comment by eidorb** [comment]
It's because of the new passkey thing.

Soz, I'm not gonna break what's working for me. I'm actually using this!

And if that ends up breaking too I'll move to a better bank 🤷

**Comment by eidorb** [comment]
It's because of the new passkey thing.

Soz, I'm not gonna break what's working for me. I'm actually using this!

And if that ends up breaking too I'll move to a better bank 🤷

**Comment by jakepronger** [comment]
> It's because of the new passkey thing.
> 
> Soz, I'm not gonna break what's working for me. I'm actually using this!
> 
> And if that ends up breaking too I'll move to a better bank 🤷 

I don't believe the new passkey method has any effect on it, however when enrolling a new device it doesn't work because UBank requires a provided api version. Many people use your repo like me and if your not willing to update it with user provided code (very simple fix) just because it's working for yourself than other people will just look at this and apply the fix for themselves. We're both using this as well.

**Comment by dnascimento** [comment]
This broken for me as well. can this be fixed please? otherwise we will fork it

**Comment by eidorb** [comment]
Give it a go peeps!

**Comment by jakepronger** [comment]
> Give it a go peeps!

All credit to you for making this repo.

**Comment by jakepronger** [comment]
> I use it in this project btw @jakepronger:
> 
> https://brodie.id.au/blog/serverless-investment-management-portfolio.html

Ohhhh, I saw this on your profile. Interesting. Not sure what I want to do but I want to integrate this with commbank and make automated scheduled (instant) payments across both banks.
